FROM archlinux:base-devel

RUN pacman -Sy && \
	pacman -S --noconfirm \
		libxrandr \
		libfdk-aac \
		ffmpeg \
		imlib2 \
		fuse3 \
		x264 \
		nasm \
		cmocka \
		check \
		libxfont2 \
		xorg-server \
		xorg-server-devel
